### ISSUE TITLE
Duplicated cell in Week 2 exercises notebook

### ISSUE THREAD

**Issue by Romoflow** [neuro4ml/exercises#2]
Hi, in Part 1 of the week 2 exercises notebook, the math description of the biexponential synapses model is duplicated (in [cell](https://github.com/neuro4ml/exercises/blob/906c0fe57db4ad49b25ed3e50563909aa604751f/w2-synapses-networks/w2-synapses-networks.ipynb#L64) 4)

**Comment by thesamovar** [comment]
Fixed, thanks!
